export const menuItemsData = [
  {
    id: 1,
    name: 'великий бургер',
    info: 'котлета воппер, сир халапеньо, хрумка цибуля',
    price: 7.99,
    img: '/images/bigBurger.png',
  },
  {
    id: 2,
    name: 'російські немовлята',
    info: 'найраща страва для справжніх бандерівців',
    price: 12.99,
    img: '/images/bowl1.png',
  },
  {
    id: 3,
    name: 'салат літній',
    info: 'кукурзка, помідорки та багато інших овочів для веганів',
    price: 6.99,
    img: '/images/bowl2.png',
  },
  {
    id: 4,
    name: 'макарони з білим соусом',
    info: 'макарони з твердих сортів пшениці зі секретним соусом',
    price: 5.99,
    img: '/images/bowl3.png',
  },
  {
    id: 5,
    name: 'макарони з метеликами',
    info: 'традиційні макарони "метелики", смак дитинства',
    price: 5.99,
    img: '/images/bowl4.png',
  },
  {
    id: 6,
    name: 'фруктова миска',
    info: 'ківі, суниця, манго та полуниця, дуже корисно',
    price: 8.99,
    img: '/images/fruits.png',
  },
  {
    id: 7,
    name: 'мюслі',
    info: 'запечені злаки, сухофрукти, горіхи та мед',
    price: 6.99,
    img: '/images/granola cereal bowl.png',
  },
  {
    id: 8,
    name: 'пальмова миска',
    info: 'полуничка, банан, злаки та фруктовий сік',
    price: 12.49,
    img: '/images/kisspng-aa-na-tigela-smoothie-aa-palm-bowl-apple-j-goji-berry-5b306ffe7baf07.9992682215299010545066.png',
  },
  {
    id: 9,
    name: 'тігела смузі',
    info: 'Полуничний смузі-боул з ківі, злаками та бананом',
    price: 11.49,
    img: '/images/kisspng-aa-na-tigela-smoothie-breakfast-juice-health-s-acai-bowl-5b11d2604db908.6695630315278946243184.png',
  },
  {
    id: 10,
    name: 'чисто сніданок',
    info: 'злаки заряджені на продуктивний день та позитив',
    price: 4.99,
    img: '/images/kisspng-breakfast-cereal-pizza-muesli-meze-vegetarian-cuis-granola-5ac48d852aeb69.1891892315228307251758.png',
  },
  {
    id: 11,
    name: 'куісіне оф Гаваї',
    info: 'справжня гавайська кухня для любителів тропічного',
    price: 11.99,
    img: '/images/kisspng-cuisine-of-hawaii-l-l-hawaiian-barbecue-shrimp-gam-frozen-chicken-5b1e62f3a9e035.2766282415287180676958.png',
  },
  {
    id: 12,
    name: 'фраєд чікен',
    info: 'смажене курча по-південному складається зі шматочків курки.',
    price: 8.99,
    img: '/images/kisspng-fried-chicken-lemon-chicken-chicken-meat-fine-dining-chicken-meat-5a940a1b75aa22.821205431519651355482.png',
  },
  {
    id: 13,
    name: 'грецкий салат',
    info: 'салат зі смачних фруктів прямо з саду власника ресторану',
    price: 6.99,
    img: '/images/kisspng-greek-salad-fruit-salad-spinach-salad-muesli-vegetable-salad-5a96f429ce9af3.7299622115198423458463.png',
  },
  {
    id: 14,
    name: 'салат чорнобаївка',
    info: 'салат із найкращих херсонських овочів разом зі свіжим м\'ясом',
    price: 7.99,
    img: '/images/kisspng-hamburger-street-food-seafood-fast-food-delicious-food-5a75083cceaf41.2676743415176192608466.png',
  },
  {
    id: 15,
    name: 'ізраїльский салат',
    info: 'салат із традиційних ізраїльских овочів, національна страва',
    price: 8.99,
    img: '/images/kisspng-israeli-salad-european-cuisine.png',
  },
  {
    id: 16,
    name: 'печений ванька',
    info: 'свіже м\'ясо прямо з під байрактару разом з білоруською бульбою',
    price: 14.99,
    img: '/images/kisspng-italian-cuisine-pizza-pasta-food-plate-healthy-food-5abb864701e2b7.3892346415222390470077.png',
  },
  {
    id: 17,
    name: 'пітса',
    info: 'соус маринару, помідори, сир моцарелла, соус песто',
    price: 9.99,
    img: '/images/pizza.png',
  },
];
